run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - goconst
    - gocritic
    - gosec
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - web
  max-issues-per-linter: 0
  max-same-issues: 0
