server:
  port: ${PORT:3001}

rampart:
  issuer: ${RAMPART_ISSUER:http://localhost:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${rampart.issuer}/.well-known/jwks.json
          issuer-uri: ${rampart.issuer}
